# To run locally:
# % pre-commit run -a
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    # These files are generated.
    exclude: "axlearn/experiments/testdata/.*"
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
