# pylint: skip-file
# pytype: skip-file
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from axlearn.ft import manager_pb2 as axlearn_dot_ft_dot_manager__pb2


class ManagerServiceStub(object):
    """FT manager service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportStatus = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/ReportStatus",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdate.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdateResponse.FromString,
        )
        self.ReportReplicaStatus = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/ReportReplicaStatus",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusUpdate.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusResponse.FromString,
        )
        self.RestartReplicaTraining = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/RestartReplicaTraining",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaRequest.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaResponse.FromString,
        )
        self.RestartTraining = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/RestartTraining",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.RestartRequest.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartResponse.FromString,
        )


class ManagerServiceServicer(object):
    """FT manager service"""

    def ReportStatus(self, request, context):
        """Worker to replica head status reporting"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportReplicaStatus(self, request, context):
        """Replica head to global head status reporting"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RestartReplicaTraining(self, request, context):
        """Global head to replica head restart command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RestartTraining(self, request, context):
        """Replica head to worker restart command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ReportStatus": grpc.unary_unary_rpc_method_handler(
            servicer.ReportStatus,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdate.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdateResponse.SerializeToString,
        ),
        "ReportReplicaStatus": grpc.unary_unary_rpc_method_handler(
            servicer.ReportReplicaStatus,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusUpdate.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusResponse.SerializeToString,
        ),
        "RestartReplicaTraining": grpc.unary_unary_rpc_method_handler(
            servicer.RestartReplicaTraining,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaRequest.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaResponse.SerializeToString,
        ),
        "RestartTraining": grpc.unary_unary_rpc_method_handler(
            servicer.RestartTraining,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartRequest.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.RestartResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "axlearn.ft.manager.ManagerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """FT manager service"""

    @staticmethod
    def ReportStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/ReportStatus",
            axlearn_dot_ft_dot_manager__pb2.StatusUpdate.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.StatusUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReportReplicaStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/ReportReplicaStatus",
            axlearn_dot_ft_dot_manager__pb2.ReplicaStatusUpdate.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.ReplicaStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RestartReplicaTraining(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/RestartReplicaTraining",
            axlearn_dot_ft_dot_manager__pb2.RestartReplicaRequest.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.RestartReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RestartTraining(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/RestartTraining",
            axlearn_dot_ft_dot_manager__pb2.RestartRequest.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.RestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
