# pylint: skip-file
# pytype: skip-file
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from axlearn.ft import manager_pb2 as axlearn_dot_ft_dot_manager__pb2

GRPC_GENERATED_VERSION = "1.63.0"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in axlearn/ft/manager_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class ManagerServiceStub(object):
    """FT manager service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportStatus = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/ReportStatus",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdate.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdateResponse.FromString,
            _registered_method=True,
        )
        self.ReportReplicaStatus = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/ReportReplicaStatus",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusUpdate.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusResponse.FromString,
            _registered_method=True,
        )
        self.RestartReplicaTraining = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/RestartReplicaTraining",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaRequest.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaResponse.FromString,
            _registered_method=True,
        )
        self.RestartTraining = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/RestartTraining",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.RestartRequest.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartResponse.FromString,
            _registered_method=True,
        )
        self.ReportPodShutdown = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/ReportPodShutdown",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.PodShutdownRequest.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.PodShutdownResponse.FromString,
            _registered_method=True,
        )
        self.RequestGlobalRestart = channel.unary_unary(
            "/axlearn.ft.manager.ManagerService/RequestGlobalRestart",
            request_serializer=axlearn_dot_ft_dot_manager__pb2.RequestGlobalRestartRequest.SerializeToString,
            response_deserializer=axlearn_dot_ft_dot_manager__pb2.RequestGlobalRestartResponse.FromString,
            _registered_method=True,
        )


class ManagerServiceServicer(object):
    """FT manager service"""

    def ReportStatus(self, request, context):
        """Worker to replica head status reporting"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportReplicaStatus(self, request, context):
        """Replica head to global head status reporting"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RestartReplicaTraining(self, request, context):
        """Global head to replica head restart command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RestartTraining(self, request, context):
        """Replica head to worker restart command"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportPodShutdown(self, request, context):
        """Pod shutdown notification"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestGlobalRestart(self, request, context):
        """Any worker to global manager: request coordinated restart of all replicas"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ReportStatus": grpc.unary_unary_rpc_method_handler(
            servicer.ReportStatus,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdate.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.StatusUpdateResponse.SerializeToString,
        ),
        "ReportReplicaStatus": grpc.unary_unary_rpc_method_handler(
            servicer.ReportReplicaStatus,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusUpdate.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.ReplicaStatusResponse.SerializeToString,
        ),
        "RestartReplicaTraining": grpc.unary_unary_rpc_method_handler(
            servicer.RestartReplicaTraining,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaRequest.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.RestartReplicaResponse.SerializeToString,
        ),
        "RestartTraining": grpc.unary_unary_rpc_method_handler(
            servicer.RestartTraining,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.RestartRequest.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.RestartResponse.SerializeToString,
        ),
        "ReportPodShutdown": grpc.unary_unary_rpc_method_handler(
            servicer.ReportPodShutdown,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.PodShutdownRequest.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.PodShutdownResponse.SerializeToString,
        ),
        "RequestGlobalRestart": grpc.unary_unary_rpc_method_handler(
            servicer.RequestGlobalRestart,
            request_deserializer=axlearn_dot_ft_dot_manager__pb2.RequestGlobalRestartRequest.FromString,
            response_serializer=axlearn_dot_ft_dot_manager__pb2.RequestGlobalRestartResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "axlearn.ft.manager.ManagerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """FT manager service"""

    @staticmethod
    def ReportStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/ReportStatus",
            axlearn_dot_ft_dot_manager__pb2.StatusUpdate.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.StatusUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReportReplicaStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/ReportReplicaStatus",
            axlearn_dot_ft_dot_manager__pb2.ReplicaStatusUpdate.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.ReplicaStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RestartReplicaTraining(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/RestartReplicaTraining",
            axlearn_dot_ft_dot_manager__pb2.RestartReplicaRequest.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.RestartReplicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RestartTraining(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/RestartTraining",
            axlearn_dot_ft_dot_manager__pb2.RestartRequest.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.RestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReportPodShutdown(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/ReportPodShutdown",
            axlearn_dot_ft_dot_manager__pb2.PodShutdownRequest.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.PodShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RequestGlobalRestart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/axlearn.ft.manager.ManagerService/RequestGlobalRestart",
            axlearn_dot_ft_dot_manager__pb2.RequestGlobalRestartRequest.SerializeToString,
            axlearn_dot_ft_dot_manager__pb2.RequestGlobalRestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
