# Copyright © 2023 Apple Inc.
#
# Some of the code in this file is adapted from:
#
# openai/gpt-2:
# Copyright (c) 2019 OpenAI.
# Licensed under a modified MIT license.

"""Tests BPE vocabulary."""

# pylint: disable=no-self-use,protected-access
import os

import tensorflow as tf
from absl.testing import absltest, parameterized

from axlearn.common.golden import load_golden
from axlearn.common.input_test_utils import tokenizers_dir
from axlearn.common.test_utils import TestCase
from axlearn.common.vocabulary_bpe import BPEVocabulary

_MODULE_NAME = "axlearn.common.vocabulary_bpe_test"

# Note: some tests contain invisible characters.
TEXTS = [
    "",
    "œ\x9c",
    "œ",
    "\x9c",
    "цIи — Боливариа́нхой",
    "  — ",
    "   — ",
    " \x0b-",
    " \x0b\x0b- ",
    " \x85- ",
    " \x85\x85- ",
    "hello world",
    "  this\r  \t\t a\ntest's  11'm'll  \tx  ",
    "ah博推zz",
    " \tHeLLo!how  \n Are yoU?  ",
    "from bert: John Johanson's house",
    # Note: this is slightly different from other occurrences, as it doesn't include the null
    # character. tf_text doesn't seem to regex_split properly with nulls.
    f"from tf_text: 株式会社 ＫＡＤＯＫＡＷＡ this  {chr(0xFFFD)}  is, å tést! SenTence `🤗` \t\t\f,  ",
    f"from tf_text: 株式会社 ＫＡＤＯ<s>ＫＡＷＡ</s> this  {chr(0xFFFD)}  is, å tést! SenTence `🤗` \t\t\f,  ",
    "<s> \thello <s world<s>test !<pad></s><mask>  \x85<s><<|endoftext|>>",
]
_TOKENIZERS = ["roberta-base", "gpt2", "opt"]


def _id_map_for(name: str) -> dict[int, int]:
    """Returns the BPEVocabulary id_map needed to satisfy seqio's pad_id=0 requirement."""
    if name in {"roberta-base", "opt"}:
        # In the original fairseq/hf vocab, we have:
        # |   0   |   1   |   2   |   3   |   4   | ...
        # |  <s>  | <pad> |  </s> | <unk> |   .   | ...
        #
        # Seqio requires that the pad token be at 0, so we remap <s> and <pad>.
        # OPT has the same mapping.
        return {0: 1, 1: 0}
    if name == "gpt2":
        # In our SPM-compatible GPT2 vocab, we have:
        # |   0   | ... |     50256     | 50257 | 50258 |
        # |   !   | ... | <|endoftext|> | <unk> | <pad> |
        #
        # Seqio requires that the pad token be at 0, so we remap ! and <pad>.
        return {0: 50258, 50258: 0}
    raise NotImplementedError(name)


def _make_vocab(name: str) -> BPEVocabulary:
    return BPEVocabulary(
        os.path.join(tokenizers_dir, f"bpe/{name}.model"),
        id_map=_id_map_for(name),
    )


class BPEVocabularyTest(TestCase):
    """Tests BPEVocabulary against frozen HuggingFace tokenizer outputs.

    Reference outputs (HF id_to_piece map, regex split, byte encoding, encoded ids
    for each text in TEXTS) are recorded in
    `axlearn.common.vocabulary_bpe_test.npz`, generated by parity-goldens'
    `_vocabulary_bpe.py`. Regenerate when adding/removing tokenizers or texts.
    """

    @parameterized.parameters(_TOKENIZERS)
    def test_id_map(self, name: str):
        vocab = _make_vocab(name)
        ref = load_golden(_MODULE_NAME, "test_id_map")[name]
        ref_vocab_size = int(ref["vocab_size"])
        ref_id_to_piece = ref["id_to_piece"]

        # GPT2 doesn't originally have UNK, PAD, or SEP. OPT lacks UNK and SEP.
        if name != "gpt2":
            self.assertEqual(vocab.vocab_size, ref_vocab_size)
        if name not in {"gpt2", "opt"}:
            self.assertEqual(
                vocab.tokenizer.id_to_piece(vocab.unk_id),
                str(ref_id_to_piece[int(ref["unk_id"])]),
            )
            self.assertEqual(
                vocab.tokenizer.id_to_piece(vocab.eos_id),
                str(ref_id_to_piece[int(ref["sep_id"])]),
            )

        # Check special tokens: <s> and <pad> are remapped for compat with seqio.
        self.assertEqual(vocab.pad_id, 0)

        # Note: seqio doesn't expose bos_id as a field.
        self.assertEqual(
            vocab.tokenizer.id_to_piece(vocab.eos_id),
            str(ref_id_to_piece[int(ref["eos_id"])]),
        )

        # Check other tokens.
        for i in range(min(vocab.vocab_size, ref_vocab_size)):
            if i not in vocab._id_map:
                self.assertEqual(vocab.tokenizer.id_to_piece(i), str(ref_id_to_piece[i]))

    def test_id_map_validation(self):
        """Some sanity checks for id_map."""
        with self.assertRaisesRegex(ValueError, "seqio expects pad_id"):
            BPEVocabulary(os.path.join(tokenizers_dir, "bpe/roberta-base.model"))

        with self.assertRaisesRegex(ValueError, "must be bijective"):
            BPEVocabulary(
                os.path.join(tokenizers_dir, "bpe/roberta-base.model"), id_map={0: 1, 1: 1}
            )

    def test_extra_ids(self):
        vocab = BPEVocabulary(
            os.path.join(tokenizers_dir, "bpe/roberta-base.model"),
            id_map={0: 1, 1: 0},
            extra_ids=2,
        )
        self.assertEqual(vocab.tokenizer.piece_to_id("▁<extra_id_0>"), vocab.vocab_size - 1)
        self.assertEqual(vocab.tokenizer.piece_to_id("▁<extra_id_1>"), vocab.vocab_size - 2)

    @parameterized.parameters(_TOKENIZERS)
    def test_py_encode_fake_data(self, name: str):
        vocab = _make_vocab(name)
        for text in TEXTS:
            ids = vocab.encode(text)
            tf_ids = vocab.encode_tf(tf.constant(text, dtype=tf.string))
            self.assertSequenceEqual(ids, tf_ids.numpy().tolist())

    @parameterized.parameters(_TOKENIZERS)
    def test_py_decode_fake_data(self, name: str):
        vocab = _make_vocab(name)
        for text in TEXTS:
            # Note: seqio decode truncates the string at first EOS, so we compare against _decode.
            self.assertEqual(text, vocab._decode(vocab.encode(text)))

    @parameterized.parameters(_TOKENIZERS)
    def test_regex_split_fake_data(self, name: str):
        vocab = _make_vocab(name)
        ref = load_golden(_MODULE_NAME, "test_regex_split_fake_data")[name]
        for i, text in enumerate(TEXTS):
            expected = [str(s) for s in ref[f"text_{i:02d}"]]
            actual = vocab._regex_split_tf(tf.constant(text, dtype=tf.string))
            actual = [x.numpy().decode("utf-8") for x in actual]
            self.assertSequenceEqual(expected, actual)

    @parameterized.parameters(_TOKENIZERS)
    def test_byte_encode_fake_data(self, name: str):
        vocab = _make_vocab(name)
        ref = load_golden(_MODULE_NAME, "test_byte_encode_fake_data")[name]
        expected = [str(s) for s in ref["byte_encoded"]]
        for text, exp in zip(TEXTS, expected):
            actual = vocab._byte_encode_tf(tf.constant([text]))[0].numpy().decode("utf-8")
            self.assertEqual(exp, actual)

    @parameterized.product(name=_TOKENIZERS, chunk_size=[1, 5])
    def test_chunk_byte_encode_fake_data(self, name: str, *, chunk_size: int):
        vocab = _make_vocab(name)
        # Chunked output is identical to byte_encoded regardless of chunk_size.
        ref = load_golden(_MODULE_NAME, "test_byte_encode_fake_data")[name]
        expected = [str(s) for s in ref["byte_encoded"]]
        for text, exp in zip(TEXTS, expected):
            actual = (
                vocab._chunk_byte_encode_tf(tf.constant([text]), chunk_size=chunk_size)[0]
                .numpy()
                .decode("utf-8")
            )
            self.assertEqual(exp, actual)

    @parameterized.product(name=_TOKENIZERS)
    def test_tokenize_detokenize_roundtrip(self, name: str):
        vocab = _make_vocab(name)
        for text in TEXTS:
            tokens = vocab._regex_split_with_ud_tokens_tf(text)
            tokens = vocab._byte_encode_tf(tokens)
            recovered = vocab.tf_tokenizer.detokenize(vocab.tf_tokenizer.tokenize(tokens))
            self.assertSequenceEqual(tokens.numpy().tolist(), recovered.numpy().tolist())

    @parameterized.parameters(_TOKENIZERS)
    def test_byte_decode_fake_data(self, name: str):
        vocab = _make_vocab(name)
        # Verify byte_encode + byte_decode recovers original.
        for text in TEXTS:
            tokens = vocab._regex_split_with_ud_tokens_tf(text)
            encoded = vocab._byte_encode_tf(tokens)
            recovered = vocab._byte_decode_tf(encoded)
            self.assertEqual(text.encode("utf-8"), tf.strings.reduce_join(recovered).numpy())

    @parameterized.parameters(_TOKENIZERS)
    def test_encode_fake_data(self, name: str):
        vocab = _make_vocab(name)
        ref = load_golden(_MODULE_NAME, "test_encode_fake_data")[name]
        for i, text in enumerate(TEXTS):
            expected = list(ref[f"text_{i:02d}"])
            actual = vocab.apply_inv_id_map_tf(vocab.encode_tf(text)).numpy().tolist()
            self.assertSequenceEqual(expected, actual)

    @parameterized.parameters(_TOKENIZERS)
    def test_decode_fake_data(self, name: str):
        vocab = _make_vocab(name)
        for text in TEXTS:
            ids = vocab.encode_tf(text)
            recovered = vocab._decode_tf(ids)
            self.assertEqual(text.encode("utf-8"), recovered.numpy())

    @parameterized.parameters(_TOKENIZERS)
    def test_decode_batch_fake_data(self, name: str):
        vocab = _make_vocab(name)
        for text in TEXTS:
            # Note: encode doesn't support batched yet.
            ids = tf.expand_dims(vocab.encode_tf(text), axis=0)
            ids = tf.tile(ids, (2, 1))
            recovered_batch = vocab._decode_tf(ids)
            for recovered in recovered_batch.numpy():
                self.assertEqual(text.encode("utf-8"), recovered)

    def test_decode_as_control_map_fake_data(self):
        vocab = BPEVocabulary(
            os.path.join(tokenizers_dir, "bpe/opt.model"),
            id_map={0: 1, 1: 0},
            decode_as_control=(0, 2),
        )
        text = "<pad></s>"
        ids = vocab.encode_tf(text)
        self.assertSequenceEqual(ids.numpy().tolist(), [0, 2])
        recovered = vocab._decode_tf(ids)

        # All of them should have been dropped.
        self.assertEqual("", recovered.numpy().decode("utf-8"))

        text = "<pad>this </s>is</s> a<pad> test"
        ids = vocab.encode_tf(text)
        recovered = vocab._decode_tf(ids)
        self.assertEqual("this is a test", recovered.numpy().decode("utf-8"))


if __name__ == "__main__":
    absltest.main()
