load("@rules_python//python:defs.bzl", "py_library")

# TODO(wyi): Consider rename __init__.py into root_module.py
py_library(
    name = "cloud",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)
